services:
  prestashop.module.favoriterider.repository.rider_repository:
    class: PrestaShop\Module\FavoriteRider\Repository\RiderRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - PrestaShop\Module\FavoriteRider\Entity\Rider