services:
  prestashop.module.favoriterider.repository.rider_repository:
    class: PrestaShop\Module\FavoriteRider\Repository\RiderRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - PrestaShop\Module\FavoriteRider\Entity\Rider
  prestashop.module.favoriterider.image.rider_image_thumbnail_provider:
    class: 'PrestaShop\Module\FavoriteRider\Image\RiderImageThumbnailProvider'
    arguments:
      - '@prestashop.core.image.parser.image_tag_source_parser'

  # form
  prestashop.module.favoriterider.type.rider:
    class: 'PrestaShop\Module\FavoriteRider\Form\RiderType'
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      - '@=service("prestashop.adapter.multistore_feature").isUsed()'
    tags:
      - { name: form.type }
  
  prestashop.module.favoriterider.upload.rider_image_uploader:
    class: 'PrestaShop\Module\FavoriteRider\Uploader\RiderImageUploader'

  prestashop.module.favoriterider.form.identifiable_object.data_provider.rider_data_provider:
    class: 'PrestaShop\Module\FavoriteRider\Form\RiderFormDataProvider'
    arguments:
      - '@prestashop.module.favoriterider.repository.rider_repository'

  prestashop.module.favoriterider.form.identifiable_object.builder.rider_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'PrestaShop\Module\FavoriteRider\Form\RiderType'
      - '@prestashop.module.favoriterider.form.identifiable_object.data_provider.rider_data_provider'

  prestashop.module.favoriterider.form.identifiable_object.data_handler.rider_form_data_handler:
    class: 'PrestaShop\Module\FavoriteRider\Form\RiderFormDataHandler'
    arguments:
      - '@prestashop.module.favoriterider.repository.rider_repository'
      - '@doctrine.orm.default_entity_manager'
      - '@prestashop.module.favoriterider.upload.rider_image_uploader'

  prestashop.module.favoriterider.form.identifiable_object.handler.rider_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.module.favoriterider.form.identifiable_object.data_handler.rider_form_data_handler'

  # grid
  prestashop.module.favoriterider.rider_grid_definition_factory:
    class: 'PrestaShop\Module\FavoriteRider\Grid\RiderGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true

  prestashop.module.favoriterider.rider_query_builder:
    class: 'PrestaShop\Module\FavoriteRider\Grid\RiderQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true

  prestashop.module.favoriterider.rider_grid_data_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory'
    arguments:
      - '@prestashop.module.favoriterider.rider_query_builder' # service id of our query builder
      - '@prestashop.core.hook.dispatcher' # every doctrine query builder needs the hook dispatcher
      - '@prestashop.core.grid.query.doctrine_query_parser' # parser to get the raw SQL query
      - 'rider_entity' #grid id
  
  prestashop.module.favoriterider.rider_grid_decorator:
    class: 'PrestaShop\Module\FavoriteRider\Grid\RiderGridDataFactory'
    arguments:
      - '@prestashop.module.favoriterider.rider_grid_data_factory'
      - '@prestashop.module.favoriterider.image.rider_image_thumbnail_provider'

  prestashop.module.favoriterider.rider_grid_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@prestashop.module.favoriterider.rider_grid_definition_factory'
      - '@prestashop.module.favoriterider.rider_grid_decorator'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'